# ==================================================
# Core Settings
# ==================================================
theme: jekyll-theme-chirpy
lang: en
timezone: Africa/Nairobi
title: Reagan Odhiambo Otieno
tagline: Data Analyst | Applied Statistician
description: >-
  Professional portfolio showcasing expertise in Python, R, SQL, and Power BI for data analysis,
  statistical modeling, and business intelligence solutions.

# ==================================================
# URL & Deployment (CRITICAL SETTINGS)
# ==================================================
url: "https://reaganotienoo.github.io"  # Use all lowercase for consistency
baseurl: ""  # Leave empty for root domains

# ==================================================
# Social & Professional Profiles
# ==================================================
github:
  username: reaganotienoO

social:
  name: Reagan Odhiambo Otieno
  email: otieni.reagan@gmail.com
  links:
    - https://www.linkedin.com/in/reagan-odhiambo-otieno1
    - https://github.com/reaganotienoO
    - https://www.datascienceportfol.io/otienireagan

# ==================================================
# Visual Customization
# ==================================================
avatar: _site/assets/prof.PNG  # Path to your profile photo (ensure correct case)
social_preview_image: false # SEO preview image
theme_mode: light  # [light | dark | empty for system default]

# ==================================================
# Content Settings
# ==================================================
toc: true  # Enable table of contents in posts
paginate: 10  # Posts per page

# ==================================================
# Optional Features (Disable if not needed)
# ==================================================
# Analytics (uncomment and fill if used)
# analytics:
#   google:
#     id: UA-XXXXXX-X

# Comments (uncomment if needed)
# comments:
#   provider: disqus
#   disqus:
#     shortname: your-disqus-shortname

# ==================================================
# Advanced Settings (Recommended not to modify)
# ==================================================
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# ==================================================
# File Management
# ==================================================
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"

include:
  - assets
