theme: jekyll-theme-chirpy

lang: en
timezone: Africa/Nairobi

title: Reagan Odhiambo Otieno
tagline: Data Analyst | Turning Data into Actionable Insights
description: >-
  Data Analyst specializing in Python, SQL, Excel, Power BI, data visualization,
  data cleaning, and transforming data into actionable business insights.

url: "https://reaganotienoo.github.io"
baseurl: ""

github:
  username: reaganotienoO

social:
  name: Reagan Odhiambo Otieno
  email: otieni.reagan@gmail.com
  links:
    - https://www.linkedin.com/in/reagan-odhiambo-otieno1
    - https://github.com/reaganotienoO
    - https://www.datascienceportfol.io/otienireagan

avatar: /assets/prof.PNG

theme_mode: dark

toc: true
paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"

include:
  - assets
