# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone (Nairobi)
timezone: Africa/Nairobi

# jekyll-seo-tag settings
title: Reagan Odhiambo Otieno

tagline: Data Analyst | Applied Statistician

description: >-
  Professional portfolio showcasing my expertise in data analysis, statistical modeling, and data visualization using Python, R, SQL, and Power BI.

url: "https://reaganotienoO.github.io/reaganotienoo.io"

github:
  username: reaganotienoO

twitter:
  username: "" # Leave empty if no Twitter

social:
  name: Reagan Odhiambo Otieno
  email: otieni.reagan@gmail.com
  links:
    - https://www.linkedin.com/in/reagan-otieno-441539351
    - https://github.com/reaganotienoO
    - https://www.datascienceportfol.io/otienireagan

# Site Verification Settings (leave empty if not using)
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# Web Analytics Settings (leave empty if not using)
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 

# Page views settings
pageviews:
  provider: 

# Theme mode (light/dark or leave empty for system preference)
theme_mode: 

# CDN settings (leave empty if not using CDN)
cdn:

# Avatar image path
avatar: /assets/img/profile.jpg

# Social preview image
social_preview_image: /assets/img/social-preview.jpg

# Table of Contents settings
toc: true

# Comments settings (leave empty if not using comments)
comments:
  provider: 

# Self-hosted assets (leave default)
assets:
  self_host:
    enabled: 
    env: 

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ Advanced settings (recommend not modifying) ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
